### ISSUE TITLE
Info_hash field

### ISSUE THREAD

**Issue by unknown--** [trumtomte/t2j#1]
It would be great to have the info_hash (sha1 hash of the info dictionary) as part of the json output

**Comment by trumtomte** [comment]
Thanks for the suggestion! It will be added in the (soon) upcoming rewrite.

**Comment by trumtomte** [comment]
The `info_hash` can now be a part of the JSON output via the `-i` flag, see the updated readme for more details. Thanks for the suggestion once again.
